### ISSUE TITLE
dpptam/map not being published

### ISSUE THREAD

**Issue by rnunziata** [alejocb/dpptam#36]
dpptam/map is not being published when i use my webcam via usb_cam. The only difference is in the header from what I can see...since running the bag file works in the example. Here are the differences.
There are no error messages. Node graph looks ok. Any idea on what is going on....the marker and other topics are ok...just the point clouds are not published.

Bag file image. 
```
header: 
  seq: 447
  stamp: 
    secs: 1426957734
    nsecs: 606139044
  frame_id: /camera_rgb_optical_frame
height: 480
width: 640
encoding: bgr8
is_bigendian: 0
step: 1920
```

usb_cam image

```
header: 
  seq: 577
  stamp: 
    secs: 1504412453
    nsecs: 846092342
  frame_id: /camera_rgb_optical_frame
height: 480
width: 640
encoding: rgb8
is_bigendian: 0
step: 1920



```
